DROP TABLE comments;
DROP TABLE posts;
DROP TABLE users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username CHARACTER VARYING(90) NOT NULL,
  first_name CHARACTER VARYING(90) DEFAULT NULL,
  last_name CHARACTER VARYING(90) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title CHARACTER VARYING(180) DEFAULT NULL,
  url CHARACTER VARYING(510) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  user_id INTEGER REFERENCES users(id)
);

CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  body CHARACTER VARYING(510) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  user_id INTEGER REFERENCES users(id),
  post_id INTEGER REFERENCES posts(id)
);